url: https://mteaudors.github.io
baseurl: /personal-website/

# Site settings
title: Mickaël Teaudors
email: mteaudors@outlook.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links

# people:
# - name: Kay Garland
#   pic: 1
#   position: Lead Designer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: stack-overflow
#       url: #

# - name: Larry Parker
#   pic: 2
#   position: Lead Marketer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: linkedin
#       url: #

# - name: Diana Petersen
#   pic: 3
#   position: Lead Developer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: google-plus
#       url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social-media:
  - title: Linkedin
    url: https://www.linkedin.com/in/mickael-teaudors
    icon: img/linkedin-icon.png
  - title: Github
    url: https://github.com/mteaudors
    icon: img/github-icon.png
  - title: Goodreads
    url: https://www.goodreads.com/user/show/97766311-mickael
    icon: img/goodreads-icon.png


# Postal address (add as many lines as necessary)
address:
  - line: Chelles, France

# Build settings
markdown: kramdown
permalink: pretty